### ISSUE TITLE
Crashes while testing build 1.0(35) 

### ISSUE THREAD

**Issue by Jaceken** [ably/asset-tracking-android-rider-app-demo#43]
Check Firebase Crashlytics for more detail:

1. [Navigator.kt line 9](https://console.firebase.google.com/u/1/project/ably-asset-tracking-demos/crashlytics/app/android:com.ably.tracking.demo.subscriber/issues/5776070f14bd7c0408ea8d140ad821ea?time=last-twenty-four-hours&sessionEventKey=62ECF39F02A3000113E5E97B07FD2188_1706785918740766310)
1. [DefaultAbly.java line 2](https://console.firebase.google.com/u/1/project/ably-asset-tracking-demos/crashlytics/app/android:com.ably.tracking.demo.subscriber/issues/8d46573aa71dcdf8937447ab91da362a?time=last-twenty-four-hours&sessionEventKey=62EB6C560092000148C39AA94A1DC36A_1706468102262732152)

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2513) by [Unito](https://www.unito.io)

**Comment by davyskiba** [comment]
@Jaceken, both linked crashes happened in the customer app according to firebase, is that correct?

The navigator one seems to come from development, it happened one time, on an Android emulator, and in the code that I think is not released yet 🤔 

The second one is a `Timeout was thrown when waiting for channel to attach` - could be caused by some network issues (I'm repeatedly getting those when using VPN), there is not much we can do to prevent that, but we probably should handle them more gracefully

**Comment by davyskiba** [comment]
I assume those crashes are not an issue - one is development crash and the other is related to invalid connection
